export type StakeholderGroupRoleType =
  | 'CLIENT_HEAD_OF_HOUSEHOLD'
  | 'CLIENT_FAMILY_MEMBER'
  | 'CLIENT_TRUSTED_USER'
  | 'AGENCY_EMPLOYEE'
  | 'AGENCY_ADMIN'
  | 'MARKETING_AGENT'
  | 'PROPERTY_OWNER'
  | 'PROPERTY_MANAGER';

export type PartnerRoleType = 'PARTNER_ACCOUNT_PRIMARY_MEMBER' | 'PARTNER_ACCOUNT_ADMIN' | 'PARTNER_ACCOUNT_MEMBER';
