export const CASE_OWNER = 'CASE_OWNER';

export enum USER_FILE_STATUS {
  DRAFT = 'UPLOAD_PENDING',
}

export enum CRITERION_FULFILLMENT_TYPE {
  ALL = 'ALL',
  ANY = 'ANY',
}

export enum CASE_CRITERION_STATUS {
  STARTED = 'STARTED',
}

export enum CASE_FILE_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
}

export enum ROLE_NAMES {
  FAMILY = "Family/Client",
  TRUSTED_USER = "Family/Trusted User",
  HPD_ADMIN = "HPD Admin Agent",
  DHS_ADMIN = "DHS Admin Agent",
  DHS_MEMBER = "DHS Team Member",
  HRA_ADMIN = "HRA Admin Agent",
  SPONSOR = "Sponsor",
  CBO_AGENT = "CBO Staffer"
}

export enum USER_ROLES {
  CLIENT = 'CLIENT',
  TRUSTED_USER = 'TRUSTED_USER',
  DHS_ADMIN = 'DHS_ADMIN',
  DHS_MEMBER = 'DHS_MEMBER',
  HRA_ADMIN = 'HRA_ADMIN',
  SPONSOR = 'SPONSOR',
  CBO_MEMBER = 'CBO_MEMBER',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  HPD_EDITOR = 'HPD_EDITOR',
  HPD_READ_ONLY = 'HPD_READ_ONLY',
  HPD_ADMIN = 'HPD_ADMIN',
}

// Users Permission.
export const CAN_ADD_CASE_FILE = [USER_ROLES.CBO_MEMBER, USER_ROLES.HPD_ADMIN, USER_ROLES.DHS_ADMIN];

export const CAN_GET_CASE = [USER_ROLES.HPD_ADMIN, USER_ROLES.DHS_ADMIN, USER_ROLES.DHS_MEMBER];
export const CAN_GET_CASE_WHEN_IN_CASE = [USER_ROLES.CBO_MEMBER, USER_ROLES.SPONSOR];

export const CAN_DOWNLOAD_USER_FILE = [
  USER_ROLES.CBO_MEMBER,
  USER_ROLES.HPD_ADMIN,
  USER_ROLES.DHS_ADMIN,
  USER_ROLES.DHS_MEMBER,
  USER_ROLES.SPONSOR,
  USER_ROLES.PLATFORM_ADMIN,
  USER_ROLES.HPD_EDITOR,
  USER_ROLES.HPD_READ_ONLY,
  USER_ROLES.HRA_ADMIN,
];
export const CAN_VIEW_DOCUMENT_STATUS = [
  USER_ROLES.SPONSOR,
  USER_ROLES.HPD_ADMIN,
  USER_ROLES.CBO_MEMBER,
  USER_ROLES.DHS_MEMBER,
];

export const CAN_GET_USER_CASE = [
  USER_ROLES.CBO_MEMBER,
  USER_ROLES.HPD_ADMIN,
  USER_ROLES.DHS_ADMIN,
  USER_ROLES.DHS_MEMBER,
  USER_ROLES.SPONSOR,
  USER_ROLES.PLATFORM_ADMIN,
  USER_ROLES.HPD_EDITOR,
  USER_ROLES.HPD_READ_ONLY,
  USER_ROLES.HRA_ADMIN,
];

export const CAN_CHANGE_APPLICATION_STATUS = [USER_ROLES.HPD_ADMIN, USER_ROLES.DHS_ADMIN];

export const CAN_VIEW_CASE_FILE_STATUS = [
  USER_ROLES.CBO_MEMBER,
  USER_ROLES.SPONSOR,
  USER_ROLES.HPD_ADMIN,
  USER_ROLES.DHS_ADMIN,
];

export const CAN_CHANGE_CASE_FILE_STATUS = [
  USER_ROLES.CBO_MEMBER,
  USER_ROLES.SPONSOR,
  USER_ROLES.HPD_ADMIN,
  USER_ROLES.DHS_ADMIN,
];
