-- AlterTable
ALTER TABLE "User" ALTER COLUMN "DOB" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "PPAcceptedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "TOSAcceptedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "UserFamilyMember" ALTER COLUMN "DOB" SET DATA TYPE TIMESTAMPTZ;
