import { ConfigRouteEntry } from 'aws-lambda-api-tools';
import { routesBaseUrlPath, routesSourceBaseDirectory } from '../../lib/utils';
import { join } from 'path';

export default [
  {
    description: 'Get user files.',
    swaggerMethodName: 'getUserFiles',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-user-files'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/{userId}/files`,
  },
  {
    description: 'Get my files.',
    swaggerMethodName: 'getMyFiles',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-my-files'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/files`,
  },
  {
    description: 'Generate user file.',
    swaggerMethodName: 'generateUserFile',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/generate-user-file'),
    method: 'POST',
    path: `${routesBaseUrlPath}/users/files/generated`,
  },
  {
    description: 'Update user file.',
    swaggerMethodName: 'updateUserFile',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/update-user-file'),
    method: 'PATCH',
    path: `${routesBaseUrlPath}/users/files`,
  },
  {
    description: 'Delete user file.',
    swaggerMethodName: 'deleteUserFile',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/delete-user-file'),
    method: 'DELETE',
    path: `${routesBaseUrlPath}/users/files`,
  },
  {
    description: 'Get user family member files.',
    swaggerMethodName: 'getUserFamilyMemberFiles',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-user-family-member-files'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/{userId}/files/family-member`,
  },
  {
    description: 'Get download url for user file.',
    swaggerMethodName: 'getUserFileDownloadUrl',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-user-file-download-url'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/files/download`,
  },
  {
    description: 'Get cases for user file.',
    swaggerMethodName: 'getUserFileCases',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-generated-file-cases'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/files/{fileId}/cases`,
  },
  {
    description: 'Update generated file',
    swaggerMethodName: 'updateGeneratedFile',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/update-generated-file'),
    method: 'PATCH',
    path: `${routesBaseUrlPath}/users/files/generated`,
  },
  {
    description: 'Get generated file download url',
    swaggerMethodName: 'getGeneratedFileDownloadUrl',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-generated-file-download-url'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/files/generated/download`,
  },
  {
    description: 'Get generated file thumbnail download url',
    swaggerMethodName: 'getGeneratedTFileThumbnailDownloadUrl',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-generated-file-thumbnail-download-url'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/files/generated/thumbnail/download`,
  },
  {
    description: 'Get generated file by id',
    swaggerMethodName: 'getGenerateFileById',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-generated-file-by-id'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/files/generated`,
  },
  {
    description: 'Delete generated file and associated files by id',
    swaggerMethodName: 'deleteGeneratedFileById',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/delete-generated-file-by-id'),
    method: 'DELETE',
    path: `${routesBaseUrlPath}/users/files/generated`,
  },
  {
    description: 'Get All possible file types',
    swaggerMethodName: 'getUserFileTypes',
    generateOpenApiDocs: true,
    handlerPath: join(routesSourceBaseDirectory, 'user-files/get-user-file-types'),
    method: 'GET',
    path: `${routesBaseUrlPath}/users/files/types`,
  },
] as Array<ConfigRouteEntry>;
