/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface BaseCase {
  AgencyCaseIdentifier?: string;
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: BaseCaseCriterion[];
  CaseNotes?: BaseCaseNote[];
  CaseType?: string;
  PercentComplete?: number;
  SSN?: string;
  Title?: string;
  id: string;
}

export interface BaseCaseCriterion {
  CaseFiles?: BaseCaseFile[];
  CaseId?: string;
  CreatedAt?: Date;
  CriterionFulfillmentStatus?: 'PENDING' | 'DONE';
  CriterionFulfillmentType?: string;
  CriterionGroupName?: string;
  CriterionSubGroupName?: string;
  Index?: string;
  LastModifiedByUser?: UserBase;
  LastModifiedByUserId?: string;
  Name?: string;
  RuleSets?: any;
  Status?: string;
  UserId?: string;
  WorkflowStageCriterion?: BaseWorkflowStageCriterion;
  WorkflowStageCriterionId?: string;
  id: string;
}

export interface BaseCaseFile {
  CaseCriterionId?: string;
  CaseId?: string;
  CreatedAt?: Date;
  CreatedByAgentUser?: UserBase;
  CreatedByAgentUserId?: string;
  CreatedByUserId?: string;
  GeneratedFile?: BaseGeneratedUserFile;
  GeneratedFileId?: string;
  ReasonForResubmit?: string;
  Status: 'PENDING' | 'UNDER_REVIEW' | 'ACCEPTED' | 'REJECT';
  id: string;
  imagesAvailable?: boolean;
}

export interface BaseCaseNote {
  AuthorUser?: UserBase;
  AuthorUserId?: string;
  CaseId?: string;
  CreatedAt?: Date;
  NoteAudienceScope?: string;
  NoteText?: string;
  ParentNoteId?: string;
  id: string;
}

export interface BaseCasePrimitives {
  CaseAttributes?: CaseAttributes;
  CaseType?: string;
  PercentComplete?: number;
  SSN?: string;
  Title?: string;
  id: string;
}

export interface BaseFamilyMember {
  DOB?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  User?: UserBase;
  UserId?: string;
  id: string;
}

export interface BaseGeneratedUserFile {
  CaseFiles?: object[];
  ContentType?: string;
  CreatedAt?: Date;
  CreatedByAgentUser?: UserBase;
  CreatedByAgentUserId?: string;
  CreatedByUser?: UserBase;
  CreatedByUserId?: string;
  Description?: string;
  FamilyMemberId?: string;
  FileType?: string;
  FromUserFiles?: BaseUserFile[];
  LastModifiedAt?: Date;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  UserFamilyMember?: BaseFamilyMember;
  id: string;
}

export interface BasePlatformActivityLogs {
  ActivityGeneratedByUserId?: string;
  ActivityType:
    | 'LOGIN'
    | 'LOGOUT'
    | 'CLIENT_VIEW_CASE_FAMILY_MEMBERS'
    | 'CLIENT_VIEW_CASE_TEAM_MEMBERS'
    | 'CLIENT_CREATE_CASE'
    | 'CLIENT_DELETE_CASE'
    | 'CLIENT_UPDATE_CASE'
    | 'CLIENT_GET_CASE_BY_ID'
    | 'ADD_CASE_FILES'
    | 'CLIENT_ADD_CASE_FILES_FAMILY_MEMBER'
    | 'CLIENT_ADD_CASE_FAMILY_MEMBERS'
    | 'CLIENT_REMOVE_CASE_FAMILY_MEMBERS'
    | 'CLIENT_REMOVE_CASE_FILES_SELF'
    | 'CLIENT_VIEW_CASE_FILE_LIST'
    | 'CLIENT_ADD_CASE_FILES_SELF'
    | 'AGENT_ADD_CASE_FILES_FAMILY_MEMBER'
    | 'CLIENT_REMOVE_CASE_FILES_FAMILY_MEMBER'
    | 'AGENT_ADD_CASE_FILE_CLIENT'
    | 'AGENT_RESUBMIT_CASE_FILES_CLIENT'
    | 'CLIENT_RESUBMIT_CASE_FILES_SELF'
    | 'CLIENT_RESUBMIT_CASE_FILES_FAMILY_MEMBER'
    | 'AGENT_RESUBMIT_CASE_FILES_FAMILY_MEMBER'
    | 'AGENT_ADD_NEW_CASE_NOTE'
    | 'AGENT_REPLY_TO_CASE_NOTE'
    | 'AGENT_CLOSE_CASE'
    | 'AGENT_REMOVE_CASE_NOTE'
    | 'CLIENT_UPDATE_PROFILE_SELF'
    | 'AGENT_UPDATE_PROFILE_SELF'
    | 'CLIENT_CREATE_FAMILY_MEMBER'
    | 'AGENT_PREVIEW_CASE_FILE'
    | 'AGENT_GET_CASE_FILE_LISTING'
    | 'CLIENT_UPDATE_FAMILY_MEMBER'
    | 'CLIENT_DELETE_FAMILY_MEMBERS'
    | 'CLIENT_GET_FAMILY_MEMBER_BY_ID'
    | 'CLIENT_GET_ALL_USER_FAMILY_MEMBERS'
    | 'CLIENT_UPLOAD_DOCUMENT_SELF'
    | 'CLIENT_UPDATE_DOCUMENT_SELF'
    | 'CLIENT_UPLOAD_DOCUMENT_FAMILY_MEMBER'
    | 'CLIENT_UPDATE_DOCUMENT_FAMILY_MEMBER'
    | 'CLIENT_DOWNLOAD_DOCUMENT_SELF'
    | 'CLIENT_DOWNLOAD_DOCUMENT_FAMILY_MEMBER'
    | 'CLIENT_DELETE_DOCUMENT_SELF'
    | 'CLIENT_DELETE_DOCUMENT_FAMILY_MEMBER'
    | 'AGENT_GET_ALL_USER_CASES'
    | 'AGENT_UPDATE_CASE_FILE_CLIENT'
    | 'CLIENT_UPDATE_CASE_FILE_SELF'
    | 'CLIENT_UPDATE_CASE_FILE_FAMILY_MEMBER'
    | 'AGENT_UPDATE_CASE_FILE_FAMILY_MEMBER'
    | 'CLIENT_GET_CASE_FAMILY_MEMBERS'
    | 'AGENT_APPROVE_DOCUMENT_CHECKLIST'
    | 'AGENT_REMOVE_CASE_WORKFLOW_CRITERIA'
    | 'AGENT_DOWNLOAD_CASE_FILE_CLIENT'
    | 'AGENT_DOWNLOAD_ALL_CASE_FILES'
    | 'AGENT_APPROVE_CASE_FILE_CLIENT'
    | 'AGENT_UPDATE_CASE_CRITERION'
    | 'AGENT_REJECT_CASE_FILE_CLIENT'
    | 'AGENT_EDIT_CASE_NOTE'
    | 'AGENT_APPROVE_CASE_FILE_FAMILY_MEMBER'
    | 'AGENT_UPLOAD_DOCUMENT_CLIENT'
    | 'AGENT_UPLOAD_DOCUMENT_FAMILY_MEMBER'
    | 'AGENT_UPDATE_DOCUMENT_CLIENT'
    | 'AGENT_UPDATE_DOCUMENT_FAMILY_MEMBER'
    | 'AGENT_REJECT_CASE_FILE_FAMILY_MEMBER'
    | 'AGENT_DOWNLOAD_CASE_FILE_FAMILY_MEMBER'
    | 'AGENT_VIEW_CASE_NOTES';
  ActivityValue: string;
  CreatedAt?: Date;
  RelatedEntity:
    | 'CASE'
    | 'USER_CASE'
    | 'CASE_FILE'
    | 'FAMILY_MEMBER'
    | 'CASE_APPLICANT'
    | 'USER_FILE'
    | 'CASE_FAMILY_MEMBER';
  User?: UserBase;
  id: string;
}

export interface BaseUploadedMediaAssetVersion {
  ContentType?: string;
  CreatedAt?: string;
  CreatedByUserId?: string;
  DeletedAt?: string;
  LastModifiedAt?: string;
  LastModifiedByUserId?: string;
  OriginalFilename?: string;
  SizeInBytes?: string;
  UserFileId?: string;
  id?: string;
}

export interface BaseUserFile {
  ActiveVersionId?: string;
  ContentType: string;
  CreatedAt?: Date;
  CreatedByUserId?: string;
  Description?: string;
  FilePath?: string;
  FileType?: string;
  FileUploadedAt?: Date;
  LastModifiedAt?: Date;
  LastModifiedByUserId?: string;
  LegacyId?: string;
  OriginalFilename: string;
  OwnerUserId?: string;
  Title: string;
  UploadUrls?: string[];
  UploadedMediaAssetVersions?: BaseUploadedMediaAssetVersion[];
  User?: UserBase;
  UserFamilyMember?: BaseFamilyMember;
  id?: string;
}

export interface BaseWorkflow {
  Description?: string;
  Name?: string;
  Type?: string;
  id: string;
}

export interface BaseWorkflowStage {
  StageName?: string;
  StagePosition?: string;
  Workflow?: BaseWorkflow;
  WorkflowId?: string;
  id: string;
}

export interface BaseWorkflowStageCriterion {
  CaseCriteria?: object[];
  CaseWorkflowStageId?: string;
  CriterionFulfillmentType?: string;
  CriterionGroupName?: string;
  CriterionSubGroupName?: string;
  Name?: string;
  WorkflowStage?: BaseWorkflowStage;
  id: string;
}

export type CaseAttributes = {
  name: string;
  value: string;
}[];

export interface StakeholderGroupRole {
  Description?: string;
  Name?:
    | 'Platform Administrator'
    | 'Platform Development'
    | 'Platform Support'
    | 'Client'
    | 'Client Trusted User'
    | 'PATH Employee'
    | 'PATH Administrator'
    | 'HPD Employee'
    | 'HPD Administrator'
    | 'DHS Employee'
    | 'DHS Administrator'
    | 'Sponsor'
    | 'CBO Supervisor'
    | 'CBO Staffer';
  StakeholderGroupId?: string;
  id?: string;
}

export interface UserBase {
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  LegacyId?: string;
  PlatformActivityLogs?: Record<string, never>[];
  StakeholderGroupRoles?: UserStakeholderGroupRole[];
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
  id?: string;
}

export interface UserStakeholderGroupRole {
  CreatedAt?: Date;
  StakeholderGroupRole?: StakeholderGroupRole;
  StakeholderGroupRoleId?: string;
  UserId?: string;
  id?: string;
}
