/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { GeneratedUserFile } from '.';

export interface AddCaseFileRequest {
  CaseCriterionId?: string;
  GeneratedFileIds: string[];
}

export interface DeleteCaseFileRequest {
  CaseCriterionId?: string;
  GeneratedFileIds: string[];
}

export type GetCaseListingResponse = {
  GeneratedFile?: GeneratedUserFile;
  ReasonForResubmit?: string;
  Status: 'PENDING' | 'UNDER_REVIEW' | 'ACCEPTED' | 'REJECT';
  id: string;
}[];

export interface LogDownloadCaseFile {
  caseFileIds: string[];
}

export interface LogPreviewCaseFile {
  caseFileId: string;
}

export interface LogViewCaseFamilyMember {
  CaseId: string;
}

export interface UpdateCaseFileRequest {
  ReasonForResubmit?: string;
  Status?: 'PENDING' | 'UNDER_REVIEW' | 'ACCEPTED' | 'REJECT';
}
