/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AddCaseFileRequest {
  UserFileIds: string[];
}

export interface DeleteCaseFileRequest {
  UserFileIds: string[];
}

export interface UpdateCaseFileRequest {
  Status: string;
}
