/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { CaseApplicant, UserFile, User } from '.';

export interface Case {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  PercentComplete?: number;
  Title?: string;
  id: string;
}

export type CaseAttributes = {
  name: string;
  value: string;
}[];

export interface CaseCriterion {
  Case?: object;
  CaseId?: string;
  LastModifiedByUser?: object;
  LastModifiedByUserId?: string;
  Status?: string;
  UserId?: string;
  WorkflowStageCriterion?: object;
  WorkflowStageCriterionId?: string;
  id: string;
}

export interface CaseFile {
  Case?: object;
  CaseId?: string;
  CreatedByUserId?: string;
  UserFile?: UserFile;
  UserFileId?: string;
  id: string;
}

export interface CaseNote {
  AuthorUser?: User;
  AuthorUserId?: string;
  CaseId?: string;
  CaseNote?: object;
  CaseNoteReplies?: object[];
  NoteAudienceScope?: string;
  NoteText?: string;
  ParentNoteId?: string;
  id: string;
}

export interface CaseTeamAssignment {
  Case?: object;
  CaseId?: string;
  CaseRole?: string;
  User?: User;
  UserId?: string;
  id: string;
}

export interface CreateCaseRequestBody {
  CaseAttributes?: CaseAttributes;
  CaseIdentifier: string;
  CaseTitle?: string;
  CaseType: string;
  FamilyMemberIds?: string[];
  WorkflowId: string;
}

export interface CreateCaseResponse {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  PercentComplete?: number;
  Title?: string;
  id: string;
}

export interface GetCaseResponse {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  PercentComplete?: number;
  Title?: string;
  id: string;
}

export type GetCaseUserFilesResponse = UserFile[];

export type GetUserFileCasesResponse = Case[];

export interface UpdateCaseRequestBody {
  AgencyCaseIdentifier?: string;
  CaseAttributes?: CaseAttributes;
  CaseTitle?: string;
  CaseType?: string;
  PercentComplete?: number;
  Status?: string;
}

export interface UpdateCaseResponse {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  PercentComplete?: number;
  Title?: string;
  id: string;
}

export type getCaseResponse = Case[];
