/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import {
  CaseApplicant,
  CaseAttributes,
  BaseCase,
  BaseCaseFile,
  UserBase,
  WorkflowStageCriterion,
  GeneratedUserFile,
  BaseCaseNote,
  BaseCasePrimitives,
} from '.';

export interface AddCaseNoteRequest {
  CaseId: string;
  NoteAudienceScope?: string;
  NoteText: string;
  ParentNodeId?: string;
}

export interface Case {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  CreatedAt?: Date;
  PercentComplete?: number;
  SSN?: string;
  Status?: string;
  Title?: string;
  id: string;
}

export type CaseCriteria = CaseCriterion[];

export interface CaseCriterion {
  Case?: BaseCase;
  CaseFiles?: BaseCaseFile[];
  CaseId?: string;
  CreatedAt?: Date;
  CriterionFulfillmentStatus?: 'PENDING' | 'DONE';
  CriterionFulfillmentType?: string;
  CriterionGroupName?: string;
  CriterionSubGroupName?: string;
  Index?: string;
  LastModifiedByUser?: UserBase;
  LastModifiedByUserId?: string;
  Name?: string;
  RuleSets?: any;
  Status?: string;
  UserId?: string;
  WorkflowStageCriterion?: WorkflowStageCriterion;
  WorkflowStageCriterionId?: string;
  id: string;
}

export interface CaseFile {
  Case?: BaseCase;
  CaseCriterion?: CaseCriterion;
  CaseCriterionId?: string;
  CaseId?: string;
  CreatedAt?: Date;
  CreatedByAgentUser?: UserBase;
  CreatedByAgentUserId?: string;
  CreatedByUserId?: string;
  GeneratedFile?: GeneratedUserFile;
  ReasonForResubmit?: string;
  Status: 'PENDING' | 'UNDER_REVIEW' | 'ACCEPTED' | 'REJECT';
  UserFileId?: string;
  id: string;
}

export interface CaseNote {
  AuthorUser?: UserBase;
  AuthorUserId?: string;
  CaseId?: string;
  CaseNote?: BaseCaseNote;
  CaseNoteReplies?: BaseCaseNote[];
  CreatedAt?: Date;
  NoteAudienceScope?: string;
  NoteText?: string;
  ParentNoteId?: string;
  id: string;
}

export interface CaseTeamAssignment {
  Case?: BaseCase;
  CaseId?: string;
  CaseRole?: string;
  User?: UserBase;
  UserId?: string;
  id: string;
  CreatedAt?: Date;
}

export interface CaseTeamAssignmentWithCasePrimitives {
  Case?: BaseCasePrimitives;
  CaseId?: string;
  CaseRole?: string;
  User?: UserBase;
  UserId?: string;
  id: string;
  CreatedAt?: Date;
}

export interface CreateCaseRequestBody {
  CaseAttributes?: CaseAttributes;
  CaseIdentifier?: string;
  CaseTitle?: string;
  CaseType: string;
  FamilyMemberIds?: string[];
  SSN?: string;
  WorkflowId: string;
}

export interface CreateCaseResponse {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  CreatedAt?: Date;
  PercentComplete?: number;
  SSN?: string;
  Status?: string;
  Title?: string;
  id: string;
}

export type CriteriaCaseFilesResponse = CaseFile[];

export type GetCaseNotesResponse = CaseNote[];

export interface GetCaseResponse {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  CreatedAt?: Date;
  PercentComplete?: number;
  SSN?: string;
  Status?: string;
  Title?: string;
  id: string;
}

export type GetCaseUserFilesResponse = GeneratedUserFile[];

export type GetCasesResponse = Case[];

export type GetUserFileCasesResponse = Case[];

export interface UpdateCaseCriterion {
  CriterionFulfillmentStatus: 'PENDING' | 'DONE';
  CriterionGroupName?: string;
  CriterionSubGroupName?: string;
  Name?: string;
}

export interface UpdateCaseNoteRequest {
  NoteText: string;
  id: string;
}

export interface UpdateCaseRequestBody {
  AgencyCaseIdentifier?: string;
  CaseAttributes?: CaseAttributes;
  CaseTitle?: string;
  CaseType?: string;
  PercentComplete?: number;
  SSN?: string;
  Status?: 'OPEN' | 'CLOSED';
}

export interface UpdateCaseResponse {
  AgencyCaseIdentifier?: string;
  CaseApplicants?: CaseApplicant[];
  CaseAttributes?: CaseAttributes;
  CaseCriteria?: CaseCriterion[];
  CaseFiles?: CaseFile[];
  CaseNotes?: CaseNote[];
  CaseTeamAssignments?: CaseTeamAssignment[];
  CaseType?: string;
  CreatedAt?: Date;
  PercentComplete?: number;
  SSN?: string;
  Status?: string;
  Title?: string;
  id: string;
}
