/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { BaseCase, BaseFamilyMember } from '.';

export interface AddCaseApplicantsResponse {
  Case?: BaseCase;
  CaseId?: string;
  UserFamilyMember?: BaseFamilyMember;
  UserFamilyMemberId?: string;
}

export type AddCaseFamilyMembersRequest = {
  UserFamilyMemberId: string;
}[];

export interface CaseApplicant {
  Case?: BaseCase;
  CaseId?: string;
  UserFamilyMember?: BaseFamilyMember;
  UserFamilyMemberId?: string;
}

export interface DeleteCaseApplicantResponse {}

export type DeleteCaseFamilyMembersRequest = {
  UserFamilyMemberId: string;
}[];
