/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type AddCaseApplicantsRequest = {
  UserFamilyMemberId: string;
}[];

export interface CaseApplicant {
  Case?: object;
  CaseId?: string;
  UserFamilyMember?: object;
  UserFamilyMemberId?: string;
}

export interface CaseApplicant {
  Case?: object;
  CaseId?: string;
  UserFamilyMember?: object;
  UserFamilyMemberId?: string;
}

export interface DeleteCaseApplicantResponse {}

export type DeleteCaseApplicantsRequest = {
  UserFamilyMemberId: string;
}[];
