/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { CaseApplicant, User, UserFile } from '.';

export interface CreateFamilyMemberRequest {
  DOB: Date;
  FirstName: string;
  LastName: string;
  Relationship: string;
}

export interface CreateFamilyMemberResponse {
  CaseApplicants?: CaseApplicant[];
  DOB?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  User?: User;
  UserFiles?: UserFile[];
  UserId?: string;
  id: string;
}

export type DeleteFamilyMemberRequest = string[];

export type DeleteFamilyMemberResponse = FamilyMember[];

export interface FamilyMember {
  CaseApplicants?: CaseApplicant[];
  DOB?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  User?: User;
  UserFiles?: UserFile[];
  UserId?: string;
  id: string;
}

export interface UpdateFamilyMemberRequest {
  Dob?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  id: string;
}

export interface UpdateFamilyMemberResponse {
  CaseApplicants?: CaseApplicant[];
  DOB?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  User?: User;
  UserFiles?: UserFile[];
  UserId?: string;
  id: string;
}
