/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Language {
  Code: string;
  CreatedAt: Date;
  Name: string;
  id: string;
}
