/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface PlatformActivityLogs {
  ActivityGeneratedByUserId?: string;
  ActivityType?: string;
  ActivityValue?: string;
  CreatedAt?: Date;
  Metadata?: object;
  RelatedId?: string;
  User?: object;
  id: string;
}
