/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UploadedMediaAssetVersion {
  ContentType: string;
  CreatedAt?: Date;
  CreatedByUserId?: string;
  LastModifiedAt?: Date;
  LastModifiedByUserId?: string;
  OriginalFilename: string;
  OwnerUserId?: string;
  SizeInBytes: number;
  id?: string;
}
