/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { BasePlatformActivityLogs, CaseTeamAssignment, FamilyMember, PlatformActivityLogs, CaseActivityLogs } from '.';

export interface CreateUserRequest {
  DOB: Date;
  Email: string;
  FirstName: string;
  LanguageIsoCode?: string;
  LastName: string;
}

export interface CreateUserResponse {
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  LegacyId?: string;
  PlatformActivityLogs?: BasePlatformActivityLogs[];
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
  id?: string;
}

export interface GetUser {
  CaseTeamAssignments?: CaseTeamAssignment[];
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  LegacyId?: string;
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
  UserFamilyMembers?: FamilyMember[];
  id?: string;
}

export interface GetUserActivitiesResponse {
  currentPage?: number;
  items?: PlatformActivityLogs[];
  pageSize?: number;
  total?: number;
  totalPages?: number;
}

export interface GetUserActivityQuery {
  activityTypes?: string;
  from?: Date;
  page?: number;
  pageSize?: number;
  to?: Date;
}

export interface GetUserActivityResponse {
  items?: CaseActivityLogs[];
  skip?: number;
  take?: number;
  total?: number;
  totalPages?: number;
}

export type GetUsesCases = {
  CaseTeamAssignments?: CaseTeamAssignment[];
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  LegacyId?: string;
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
  id?: string;
}[];

export interface UpdateUserRequest {
  DOB?: Date | null;
  Email?: string;
  FirstName?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  PPAcceptedAt?: Date;
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
}

export interface UpdateUserResponse {
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  LegacyId?: string;
  PlatformActivityLogs?: BasePlatformActivityLogs[];
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
  id?: string;
}

export interface User {
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  LegacyId?: string;
  PlatformActivityLogs?: BasePlatformActivityLogs[];
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
  id?: string;
}

export interface UserCaseItem {
  CaseTeamAssignments?: CaseTeamAssignment[];
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LanguageIsoCode?: string;
  LastName?: string;
  LegacyId?: string;
  TOSAccepted?: boolean;
  TOSAcceptedAt?: Date;
  id?: string;
}
