/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { CaseApplicant, User, UserFile } from '.';

export interface CreateFamilyMemberRequest {
  DOB: Date;
  FirstName: string;
  LastName: string;
  Relationship: string;
}

export type DeleteFamilyMemberRequest = string[];

export type DeleteUsersFamilyResponse = UserFamily[];

export interface UpdateUserFamilyRequest {
  Dob?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  id: string;
}

export interface UserFamily {
  CaseApllicants?: CaseApplicant[];
  DOB?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  User?: User;
  UserFiles?: UserFile[];
  UserId?: string;
  id: string;
}

export interface UserFamily {
  CaseApllicants?: CaseApplicant[];
  DOB?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  User?: User;
  UserFiles?: UserFile[];
  UserId?: string;
  id: string;
}

export interface UserFamily {
  CaseApllicants?: CaseApplicant[];
  DOB?: Date;
  FirstName?: string;
  LastName?: string;
  Relationship?: string;
  User?: User;
  UserFiles?: UserFile[];
  UserId?: string;
  id: string;
}
