/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { PlatformActivityLogs, Workflow } from '.';

export interface AddWorkFlowRequest {
  WorkflowId: string;
}

export interface AddWorkFlowResponse {
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LastName?: string;
  LegacyId?: string;
  id?: string;
}

export interface CreateUserRequest {
  DOB: Date;
  Email: string;
  FirstName: string;
  LanguageId: string;
  LastName: string;
  Workflows?: string[];
}

export interface CreateUserResponse {
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LastName?: string;
  LegacyId?: string;
  id?: string;
}

export interface DeleteWorkFlowRequest {
  WorkflowId: string;
}

export interface DeleteWorkFlowResponse {
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LastName?: string;
  LegacyId?: string;
  id?: string;
}

export interface GetUserActivityQuery {
  filters?: {
    fromDate?: Date;
    toDate?: Date;
  };
  limit?: number;
  page?: number;
}

export interface GetUserActivityResponse {
  items?: PlatformActivityLogs[];
  limit?: number;
  page?: number;
  total?: number;
}

export type GetUserWorkFlowsResponse = Workflow[];

export interface UpdateUserRequest {
  DOB?: Date;
  Email?: string;
  FirstName?: string;
  LanguageId?: string;
  LastName?: string;
  PPAcceptedAt?: Date;
  TOSAcceptedAt?: Date;
}

export interface UpdateUserResponse {
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LastName?: string;
  LegacyId?: string;
  id?: string;
}

export interface User {
  Email?: string;
  FirstName?: string;
  IdpId?: string;
  LastName?: string;
  LegacyId?: string;
  id?: string;
}
