/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { BaseCaseFile, UserBase, BaseUserFile, BaseFamilyMember, UploadedMediaAssetVersion } from '.';

export interface CreateUserFileRequest {
  CaseCriterionId?: string;
  DeletedFiles?: string[];
  Description?: string;
  FileType?: string;
  Files: {
    ContentType: string;
    OriginalFilename: string;
    PageNumber: number;
    SizeInBytes: number;
    id: string;
  }[];
  FilesOrder?: {
    id: string;
    old: boolean;
  }[];
  ForUserId?: string;
  GeneratedFileId?: string;
  Title: string;
  UserFamilyMemberId?: string;
}

export interface CreateUserFileResponse {
  UserFiles?: UserFile[];
}

export interface DeleteUserFileRequest {
  id: string;
}

export interface GeneratedUserFile {
  CaseFiles?: BaseCaseFile[];
  ContentType?: string;
  CreatedAt?: Date;
  CreatedByAgentUser?: UserBase;
  CreatedByAgentUserId?: string;
  CreatedByUser?: UserBase;
  CreatedByUserId?: string;
  Description?: string;
  FamilyMemberId?: string;
  FileType?: string;
  FromUserFiles?: BaseUserFile[];
  LastModifiedAt?: Date;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  UserFamilyMember?: BaseFamilyMember;
  id: string;
}

export interface GeneratedUserFile {
  CaseFiles?: BaseCaseFile[];
  ContentType?: string;
  CreatedAt?: Date;
  CreatedByAgentUser?: UserBase;
  CreatedByAgentUserId?: string;
  CreatedByUser?: UserBase;
  CreatedByUserId?: string;
  Description?: string;
  FamilyMemberId?: string;
  FileType?: string;
  FromUserFiles?: BaseUserFile[];
  LastModifiedAt?: Date;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  UserFamilyMember?: BaseFamilyMember;
  id: string;
}

export type GetUserFileTypesResponse = {
  documentGroup: string;
  documentName: string;
}[];

export type GetUserFilesResponse = UserFile[];

export interface UpdateGeneratedFileRequest {
  ContentType?: string;
  Description?: string;
  File?: Record<string, never>;
  FileType?: string;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  id: string;
}

export interface UpdateGeneratedFileResponse {
  CaseFiles?: BaseCaseFile[];
  ContentType?: string;
  CreatedAt?: Date;
  CreatedByAgentUser?: UserBase;
  CreatedByAgentUserId?: string;
  CreatedByUser?: UserBase;
  CreatedByUserId?: string;
  Description?: string;
  FamilyMemberId?: string;
  FileType?: string;
  FromUserFiles?: BaseUserFile[];
  LastModifiedAt?: Date;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  UserFamilyMember?: BaseFamilyMember;
  id: string;
}

export interface UpdateUserFileRequest {
  CaseCriterionId?: string;
  ContentType?: string;
  ForUserId?: string;
  OriginalFilename?: string;
  PageNumber?: number;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  UserFamilyMemberId?: string;
  id: string;
}

export interface UpdateUserFileResponse {
  ActiveVersionId?: string;
  ContentType: string;
  CreatedAt?: Date;
  CreatedByUserId?: string;
  FilePath?: string;
  FileType?: string;
  FileUploadedAt?: Date;
  GeneratedFile?: GeneratedUserFile;
  GeneratedFileId?: string;
  LastModifiedAt?: Date;
  LastModifiedByUserId?: string;
  LegacyId?: string;
  OriginalFilename: string;
  OwnerUserId?: string;
  Title: string;
  UploadUrl?: string;
  UploadUrls?: string[];
  UploadedMediaAssetVersions?: UploadedMediaAssetVersion[];
  UserFamilyMember?: BaseFamilyMember;
  id?: string;
  oldId?: string;
}

export interface UserFile {
  ActiveVersionId?: string;
  ContentType: string;
  CreatedAt?: Date;
  CreatedByUserId?: string;
  FilePath?: string;
  FileType?: string;
  FileUploadedAt?: Date;
  GeneratedFile?: GeneratedUserFile;
  GeneratedFileId?: string;
  LastModifiedAt?: Date;
  LastModifiedByUserId?: string;
  LegacyId?: string;
  OriginalFilename: string;
  OwnerUserId?: string;
  Title: string;
  UploadUrl?: string;
  UploadUrls?: string[];
  UploadedMediaAssetVersions?: UploadedMediaAssetVersion[];
  UserFamilyMember?: BaseFamilyMember;
  id?: string;
  oldId?: string;
}

export interface UserFileDownloadResponse {
  downloadUrl?: string;
}
