/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CreateUserFileRequest {
  Files: {
    ContentType: string;
    OriginalFilename: string;
    PageNumber: number;
    SizeInBytes: number;
  }[];
  Title: string;
  UserFamilyMemberId?: string;
}

export interface CreateUserFileResponse {
  UserFiles?: UserFile[];
}

export interface DeleteUserFileRequest {
  id: string;
}

export interface GeneratedUserFile {
  ContentType?: string;
  CreatedAt?: Date;
  LastModifiedAt?: Date;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  id: string;
}

export type GetUserFilesResponse = UserFile[];

export interface UpdateGeneratedFileRequest {
  ContentType?: string;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  id: string;
}

export interface UpdateGeneratedFileResponse {
  ContentType?: string;
  CreatedAt?: Date;
  LastModifiedAt?: Date;
  OriginalFilename?: string;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  id: string;
}

export interface UpdateUserFileRequest {
  ContentType?: string;
  OriginalFilename?: string;
  PageNumber?: number;
  SizeInBytes?: number;
  Status?: string;
  Title?: string;
  UserFamilyMemberId?: string;
  id: string;
}

export interface UpdateUserFileResponse {
  ActiveVersionId?: string;
  ContentType: string;
  CreatedAt?: Date;
  CreatedByUserId?: string;
  LastModifiedAt?: Date;
  LastModifiedByUserId?: string;
  LegacyId?: string;
  OriginalFilename: string;
  OwnerUserId?: string;
  Title: string;
  UploadUrl?: string;
  UploadUrls?: string[];
  UploadedMediaAssetVersions?: object[];
  id?: string;
}

export interface UserFile {
  ActiveVersionId?: string;
  ContentType: string;
  CreatedAt?: Date;
  CreatedByUserId?: string;
  LastModifiedAt?: Date;
  LastModifiedByUserId?: string;
  LegacyId?: string;
  OriginalFilename: string;
  OwnerUserId?: string;
  Title: string;
  UploadUrl?: string;
  UploadUrls?: string[];
  UploadedMediaAssetVersions?: object[];
  id?: string;
}

export interface UserFileDownloadResponse {
  downloadUrl?: string;
}
