/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Workflow {
  Description?: string;
  Name?: string;
  WorkflowStages?: WorkflowStage[];
  id: string;
}

export interface WorkflowStage {
  StageName?: string;
  Workflow?: object;
  WorkflowId?: string;
  WorkflowStateCriteria?: WorkflowStageCriterion[];
  id: string;
}

export interface WorkflowStageCriterion {
  CaseCriteria?: object[];
  CaseWorkflowStageId?: string;
  CriterionFulfillmentType?: string;
  Name?: string;
  WorkflowStage?: object;
  id: string;
}
