-- AlterTable
ALTER TABLE "Case" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "CaseApplicant" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "CaseCriterion" ADD COLUMN     "CreatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "CaseFile" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "CaseNote" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "CaseTeamAssignment" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "GeneratedFile" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Language" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "PlatformActivityLog" ADD COLUMN     "LastModifiedAt" TIMESTAMPTZ,
ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "StakeholderGroup" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "StakeholderGroupRole" ADD COLUMN     "LastModifiedAt" TIMESTAMPTZ,
ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "UploadedMediaAssetVersion" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "UserAttribute" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "UserFamilyMember" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "UserFile" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "UserWorkflow" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Workflow" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "WorkflowStage" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "WorkflowStageCriterion" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "LastModifiedAt" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "DeletedAt" SET DATA TYPE TIMESTAMPTZ;
